# Create files

In [172]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as sts
import seaborn as sns
import geopandas as gpd
from geopandas import GeoDataFrame

import warnings
warnings.simplefilter("ignore")
pd.set_option('display.max_columns', None)

In [193]:
data=pd.read_excel("G:\My Drive\INVESTIGACION\SEGUIMIENTO ESTUDIANTES\PDG\TESIS Emanuel - Ing. Geológica 2020/Eng-MorfometriaCuencasAbanicos3032.xlsx", engine='openpyxl')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 56 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   ID                                             304 non-null    int64
 1   Fan area (km^2)                                304 non-null    float64
 2   Fan perimeter (km)                             304 non-null    float64
 3   Fan length (km)                                304 non-null    float64
 4   Fan width (km)                                 304 non-null    float64
 5   Form factor of fan                             304 non-null    float64
 6   Altura max (km)                                304 non-null    float64
 7   Altura min (km)                                304 non-null    float64
 8   Fan relief (km)                                304 non-null    float64
 9   Fan slope(°)                                   304 non-null    float64
 10  Pendiente media abanico (°)                    304 non-null    float64
 11  Fan profile curvature                          304 non-null    float64
 12  Fan planform curvature                         304 non-null    float64
 13  Fan ruggednes                                  304 non-null    float64
 14  Fan volume (km^3)                              304 non-null    float64
 15  Tipo de Abanico                                304 non-null    object
 16  Tipo de asentamiento                           304 non-null    object
 17  Poblado                                        304 non-null    object
 18  Cordillera                                     304 non-null    object
 19  Main stream order                              304 non-null    int64
 20  Number of streams                              304 non-null    int64
 21   Stream length (km)                            304 non-null    float64
 22  Main stream length (km)                        304 non-null    float64
 23   Stream length ratio                           304 non-null    float64
 24  Bifurcation ratio                              304 non-null    object
 25   Ro Coefficient                                304 non-null    float64
 26  Length of catchmen (km)                        304 non-null    float64
 27  Unnamed: 27                                    0 non-null      float64
 28  Catchment area (km^2)                          304 non-null    float64
 29  Catchment perimeter (km)                       304 non-null    float64
 30  Form factor                                    304 non-null    float64
 31   Elongation ratio                              304 non-null    float64
 32  Circularity ratio                              304 non-null    float64
 33  Compactness coefficien                         304 non-null    float64
 34  Texture ratio                                  304 non-null    float64
 35  Fitness ratio                                  304 non-null    float64
 36  Wandering ratio                                304 non-null    float64
 37  Stream frequency                               304 non-null    float64
 38  Drainage density                               304 non-null    float64
 39  Constant of channel Maintenance                304 non-null    float64
 40  Drainage intensity                             304 non-null    float64
 41  Infiltration numbe                             304 non-null    float64
 42  Torrentiality coefficient                      304 non-null    float64
 43  Length of overland flow                        304 non-null    float64
 44  Catchment relief (km)                          304 non-null    float64
 45   Slope  of  the  catchment  channel (°)        304 non-null    float64
 46  Mean basin slope (°)                           304 non-null    float64
 47  Theta angle                                    304 non-null    float64
 48  Ruggedness number                              304 non-null    float64
 49  Melton index                                   304 non-null    float64
 50  Unidad geologica                               304 non-null    object
 51  Litologia                                      304 non-null    object
 52  Subzona hidrografica                           304 non-null    object
 53  Type of Catchment, according to Arango (2021)  304 non-null    object
 54  Torrential flow reports                        304 non-null    object
 55  theta                                          304 non-null    float64
dtypes: float64(43), int64(3), object(10)
memory usage: 133.1+ KB

In [194]:
data.index[data["Bifurcation ratio"]=="1.,5"]

Index([79], dtype='int64')

In [195]:
data.loc[79, "Bifurcation ratio"] = 1.5

In [196]:
data["Bifurcation ratio"]=data["Bifurcation ratio"].astype(float)

In [197]:
data=data.drop(columns=["Unnamed: 27","theta"])

In [198]:
data1=pd.read_excel("G:\My Drive\INVESTIGACION\SEGUIMIENTO ESTUDIANTES\PDG\TESIS Emanuel - Ing. Geológica 2020/Morfometria_Cuencas_Abanicos_NorthernAndes.xlsx", engine='openpyxl')
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 54 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ID                                       304 non-null    int64
 1   Fan area (km^2)                          304 non-null    float64
 2   Fan perimeter (km)                       304 non-null    float64
 3   Fan length (km)                          304 non-null    float64
 4   Fan width (km)                           304 non-null    float64
 5   Form factor of fan                       304 non-null    float64
 6   Altura max (km)                          304 non-null    float64
 7   Altura min (km)                          304 non-null    float64
 8   Fan relief (km)                          304 non-null    float64
 9   Fan slope(°)                             304 non-null    float64
 10  Fan inclination (°)                      304 non-null    float64
 11  Fan profile curvature                    304 non-null    float64
 12  Fan planform curvature                   304 non-null    float64
 13  Fan ruggednes                            304 non-null    float64
 14  Fan volume (km^3)                        304 non-null    float64
 15  Tipo de Abanico                          304 non-null    object
 16  Tipo de asentamiento                     304 non-null    object
 17  Poblado                                  304 non-null    object
 18  Cordillera                               304 non-null    object
 19  Main stream order                        304 non-null    int64
 20  Number of streams                        304 non-null    int64
 21   Stream length (km)                      304 non-null    float64
 22  Main stream length (km)                  304 non-null    float64
 23   Stream length ratio                     304 non-null    float64
 24  Bifurcation ratio                        304 non-null    object
 25   Ro Coefficient                          304 non-null    float64
 26  Length of catchmen (km)                  304 non-null    float64
 27  Catchment area (km^2)                    304 non-null    float64
 28  Catchment perimeter (km)                 304 non-null    float64
 29  Form factor                              304 non-null    float64
 30   Elongation ratio                        304 non-null    float64
 31  Circularity ratio                        304 non-null    float64
 32  Compactness coefficien                   304 non-null    float64
 33  Texture ratio                            304 non-null    float64
 34  Fitness ratio                            304 non-null    float64
 35  Wandering ratio                          304 non-null    float64
 36  Stream frequency                         304 non-null    float64
 37  Drainage density                         304 non-null    float64
 38  Constant of channel Maintenance          304 non-null    float64
 39  Drainage intensity                       304 non-null    float64
 40  Infiltration numbe                       304 non-null    float64
 41  Torrentiality coefficient                304 non-null    float64
 42  Length of overland flow                  304 non-null    float64
 43  Catchment relief (km)                    304 non-null    float64
 44   Slope  of  the  catchment  channel (°)  304 non-null    float64
 45  Mean basin slope (°)                     304 non-null    float64
 46  Relief ratio                             304 non-null    float64
 47  Ruggedness number                        304 non-null    float64
 48  Melton index                             304 non-null    float64
 49  Unidad geologica                         304 non-null    object
 50  Litologia                                304 non-null    object
 51  Subzona hidrografica                     304 non-null    object
 52  Catchment                                304 non-null    object
 53  Torrential flow reports                  304 non-null    object
dtypes: float64(41), int64(3), object(10)
memory usage: 128.4+ KB

In [199]:
data["Relief ratio"]=data1["Relief ratio"]
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 55 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   ID                                             304 non-null    int64
 1   Fan area (km^2)                                304 non-null    float64
 2   Fan perimeter (km)                             304 non-null    float64
 3   Fan length (km)                                304 non-null    float64
 4   Fan width (km)                                 304 non-null    float64
 5   Form factor of fan                             304 non-null    float64
 6   Altura max (km)                                304 non-null    float64
 7   Altura min (km)                                304 non-null    float64
 8   Fan relief (km)                                304 non-null    float64
 9   Fan slope(°)                                   304 non-null    float64
 10  Pendiente media abanico (°)                    304 non-null    float64
 11  Fan profile curvature                          304 non-null    float64
 12  Fan planform curvature                         304 non-null    float64
 13  Fan ruggednes                                  304 non-null    float64
 14  Fan volume (km^3)                              304 non-null    float64
 15  Tipo de Abanico                                304 non-null    object
 16  Tipo de asentamiento                           304 non-null    object
 17  Poblado                                        304 non-null    object
 18  Cordillera                                     304 non-null    object
 19  Main stream order                              304 non-null    int64
 20  Number of streams                              304 non-null    int64
 21   Stream length (km)                            304 non-null    float64
 22  Main stream length (km)                        304 non-null    float64
 23   Stream length ratio                           304 non-null    float64
 24  Bifurcation ratio                              304 non-null    float64
 25   Ro Coefficient                                304 non-null    float64
 26  Length of catchmen (km)                        304 non-null    float64
 27  Catchment area (km^2)                          304 non-null    float64
 28  Catchment perimeter (km)                       304 non-null    float64
 29  Form factor                                    304 non-null    float64
 30   Elongation ratio                              304 non-null    float64
 31  Circularity ratio                              304 non-null    float64
 32  Compactness coefficien                         304 non-null    float64
 33  Texture ratio                                  304 non-null    float64
 34  Fitness ratio                                  304 non-null    float64
 35  Wandering ratio                                304 non-null    float64
 36  Stream frequency                               304 non-null    float64
 37  Drainage density                               304 non-null    float64
 38  Constant of channel Maintenance                304 non-null    float64
 39  Drainage intensity                             304 non-null    float64
 40  Infiltration numbe                             304 non-null    float64
 41  Torrentiality coefficient                      304 non-null    float64
 42  Length of overland flow                        304 non-null    float64
 43  Catchment relief (km)                          304 non-null    float64
 44   Slope  of  the  catchment  channel (°)        304 non-null    float64
 45  Mean basin slope (°)                           304 non-null    float64
 46  Theta angle                                    304 non-null    float64
 47  Ruggedness number                              304 non-null    float64
 48  Melton index                                   304 non-null    float64
 49  Unidad geologica                               304 non-null    object
 50  Litologia                                      304 non-null    object
 51  Subzona hidrografica                           304 non-null    object
 52  Type of Catchment, according to Arango (2021)  304 non-null    object
 53  Torrential flow reports                        304 non-null    object
 54  Relief ratio                                   304 non-null    float64
dtypes: float64(43), int64(3), object(9)
memory usage: 130.8+ KB

In [200]:
df=data.rename(columns={'Fan area (km^2)':"$A_f$", 'Fan perimeter (km)':"$P_f$", 'Fan length (km)':"$L_f$",
       'Fan width (km)':"$W_f$", 'Form factor of fan':"$Ff_f$", 'Altura max (km)':"$Hmax_f$",
   'Altura min (km)':"$Hmin_f$", 'Fan relief (km)':"$Rel_f$", 'Fan slope(°)':"$Sn_f$",
       'Pendiente media abanico (°)':"$Sd_f$", 'Fan profile curvature':"$V_{cur.}$",
       'Fan planform curvature':"$H_{cur.}$", 'Fan ruggednes ':"$Rug_f$", 'Fan volume (km^3)':"$Vol.$",
       'Tipo de Abanico':"Type", 'Tipo de asentamiento':"Settlement", 'Poblado':"People", 'Cordillera':"Cordillera",
       'Main stream order':"$\hat{S}o$", 'Number of streams ':"Sn", ' Stream length (km)':"Sl",
       'Main stream length (km)':"$Sl_{m}$", ' Stream length ratio':"Slr", "Bifurcation ratio":"Br",' Ro Coefficient':"Ro", 
        'Length of catchmen (km)':"$L_c$", 'Catchment area (km^2)':"$A_c$",
       'Catchment perimeter (km)':"$P_c$", 'Form factor':"$Ff_c$", ' Elongation ratio':"Er","Circularity ratio":"Cr",
       'Compactness coefficien':"Cc",'Constant of channel Maintenance':"Mc","Texture ratio":"Tr","Fitness ratio":"Fr","Wandering ratio":"Wt",
        "Stream frequency":"Sf","Drainage density":"Dd","Drainage intensity":"Di","Length of overland flow":"Lof","Catchment relief (km)":"$C_r$",
       'Infiltration numbe':"In", "Torrentiality coefficient":"Tc",' Slope  of  the  catchment  channel (°)':"$Sc_c$", 'Mean basin slope (°)':"$Sh_c$",
       'Theta angle':"$\theta$", 'Ruggedness number':"$R_c$", 'Melton index':"Im", 'Unidad geologica':"Geology",
       'Litologia':"Lithology", 'Subzona hidrografica':"Basin",
       'Type of Catchment, according to Arango (2021)':"Torrential",
       'Torrential flow reports':"Reports","Relief ratio":"Rr"})

In [201]:
df.head(2)

,ID,$A_f$,$P_f$,$L_f$,$W_f$,$Ff_f$,$Hmax_f$,$Hmin_f$,$Rel_f$,$Sn_f$,$Sd_f$,$V_{cur.}$,$H_{cur.}$,$Rug_f$,$Vol.$,Type,Settlement,People,Cordillera,$\hat{S}o$,Sn,Sl,$Sl_{m}$,Slr,Br,Ro,$L_c$,$A_c$,$P_c$,$Ff_c$,Er,Cr,Cc,Tr,Fr,Wt,Sf,Dd,Mc,Di,In,Tc,Lof,$C_r$,$Sc_c$,$Sh_c$,$\theta$,$R_c$,Im,Geology,Lithology,Basin,Torrential,Reports,Rr
0,0,0.240791,2.53465,0.75725,0.62833,0.419915,0.699,0.667,0.032,4.225817,5.6904,-0.0215,-0.0171,0.7331,0.025375,Aluvial,Casas rurales dispersas,Si,Occidental,4,449,100.628,3.190,4.716946,4.011675,1.175805,3.359,12.503,15.399,1.108139,1.187824,0.662581,1.237248,14.806156,0.207156,0.949687,35.911381,8.048308,0.124250,4.461979,289.025872,18.235623,0.062125,0.311,9.749216,11.165,0.351,1.387675,0.087954,FormacionAmaga,Sedimentaria detritica,Rio Cauca,No torrential,Catchments with no torrential flow reports,0.092587
1,1,0.159653,2.15590,0.78937,0.39793,0.256222,0.693,0.654,0.039,4.940649,6.2614,-0.0066,-0.0185,0.7898,0.032237,Aluvial,Sin asentamientos,No,Occidental,4,129,24.441,1.805,1.481206,1.178194,1.257184,1.987,2.063,5.928,0.522521,0.815656,0.737722,1.172546,6.578947,0.304487,0.908405,62.530296,11.847310,0.084407,5.278016,740.815781,18.904508,0.042204,0.317,17.562327,13.005,0.352,1.673131,0.220704,Formacion Amaga,Sedimentaria detritica,Rio Cauca,Torrential,Catchments with no torrential flow reports,0.159537

In [202]:
df.to_excel("G:\My Drive\INVESTIGACION\PAPERS\ELABORACION\PAPER_FanCatchments/Data/Morphometry/fan.xlsx", index=False)
#sep='\t', encoding='utf-8', index=False, header=True, mode="w"

In [203]:
cat=gpd.read_file('G:/My Drive/INVESTIGACION/POSDOC/Data/Vector/torre_catchments.shp')
cat=cat.rename(columns={'id':'ID'})
cat=cat[["ID","geometry"]]
cat.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        304 non-null    int64
 1   geometry  304 non-null    geometry
dtypes: geometry(1), int64(1)
memory usage: 4.9 KB

In [204]:
df_cat=df.merge(cat, on='ID')
gdf=GeoDataFrame(df_cat, crs="EPSG:32618", geometry='geometry')
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 56 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          304 non-null    int64
 1   $A_f$       304 non-null    float64
 2   $P_f$       304 non-null    float64
 3   $L_f$       304 non-null    float64
 4   $W_f$       304 non-null    float64
 5   $Ff_f$      304 non-null    float64
 6   $Hmax_f$    304 non-null    float64
 7   $Hmin_f$    304 non-null    float64
 8   $Rel_f$     304 non-null    float64
 9   $Sn_f$      304 non-null    float64
 10  $Sd_f$      304 non-null    float64
 11  $V_{cur.}$  304 non-null    float64
 12  $H_{cur.}$  304 non-null    float64
 13  $Rug_f$     304 non-null    float64
 14  $Vol.$      304 non-null    float64
 15  Type        304 non-null    object
 16  Settlement  304 non-null    object
 17  People      304 non-null    object
 18  Cordillera  304 non-null    object
 19  $\hat{S}o$  304 non-null    int64
 20  Sn          304 non-null    int64
 21  Sl          304 non-null    float64
 22  $Sl_{m}$    304 non-null    float64
 23  Slr         304 non-null    float64
 24  Br          304 non-null    float64
 25  Ro          304 non-null    float64
 26  $L_c$       304 non-null    float64
 27  $A_c$       304 non-null    float64
 28  $P_c$       304 non-null    float64
 29  $Ff_c$      304 non-null    float64
 30  Er          304 non-null    float64
 31  Cr          304 non-null    float64
 32  Cc          304 non-null    float64
 33  Tr          304 non-null    float64
 34  Fr          304 non-null    float64
 35  Wt          304 non-null    float64
 36  Sf          304 non-null    float64
 37  Dd          304 non-null    float64
 38  Mc          304 non-null    float64
 39  Di          304 non-null    float64
 40  In          304 non-null    float64
 41  Tc          304 non-null    float64
 42  Lof         304 non-null    float64
 43  $C_r$       304 non-null    float64
 44  $Sc_c$      304 non-null    float64
 45  $Sh_c$      304 non-null    float64
 46  $	heta$     304 non-null    float64
 47  $R_c$       304 non-null    float64
 48  Im          304 non-null    float64
 49  Geology     304 non-null    object
 50  Lithology   304 non-null    object
 51  Basin       304 non-null    object
 52  Torrential  304 non-null    object
 53  Reports     304 non-null    object
 54  Rr          304 non-null    float64
 55  geometry    304 non-null    geometry
dtypes: float64(43), geometry(1), int64(3), object(9)
memory usage: 133.1+ KB

In [205]:
gdf.head(2)

,ID,$A_f$,$P_f$,$L_f$,$W_f$,$Ff_f$,$Hmax_f$,$Hmin_f$,$Rel_f$,$Sn_f$,$Sd_f$,$V_{cur.}$,$H_{cur.}$,$Rug_f$,$Vol.$,Type,Settlement,People,Cordillera,$\hat{S}o$,Sn,Sl,$Sl_{m}$,Slr,Br,Ro,$L_c$,$A_c$,$P_c$,$Ff_c$,Er,Cr,Cc,Tr,Fr,Wt,Sf,Dd,Mc,Di,In,Tc,Lof,$C_r$,$Sc_c$,$Sh_c$,$\theta$,$R_c$,Im,Geology,Lithology,Basin,Torrential,Reports,Rr,geometry
0,0,0.240791,2.53465,0.75725,0.62833,0.419915,0.699,0.667,0.032,4.225817,5.6904,-0.0215,-0.0171,0.7331,0.025375,Aluvial,Casas rurales dispersas,Si,Occidental,4,449,100.628,3.190,4.716946,4.011675,1.175805,3.359,12.503,15.399,1.108139,1.187824,0.662581,1.237248,14.806156,0.207156,0.949687,35.911381,8.048308,0.124250,4.461979,289.025872,18.235623,0.062125,0.311,9.749216,11.165,0.351,1.387675,0.087954,FormacionAmaga,Sedimentaria detritica,Rio Cauca,No torrential,Catchments with no torrential flow reports,0.092587,"POLYGON ((432423.736 628076.247, 432395.040 62..."
1,1,0.159653,2.15590,0.78937,0.39793,0.256222,0.693,0.654,0.039,4.940649,6.2614,-0.0066,-0.0185,0.7898,0.032237,Aluvial,Sin asentamientos,No,Occidental,4,129,24.441,1.805,1.481206,1.178194,1.257184,1.987,2.063,5.928,0.522521,0.815656,0.737722,1.172546,6.578947,0.304487,0.908405,62.530296,11.847310,0.084407,5.278016,740.815781,18.904508,0.042204,0.317,17.562327,13.005,0.352,1.673131,0.220704,Formacion Amaga,Sedimentaria detritica,Rio Cauca,Torrential,Catchments with no torrential flow reports,0.159537,"POLYGON ((430194.835 632310.913, 430221.709 63..."

In [206]:
gdf.to_file('G:\My Drive\INVESTIGACION\PAPERS\ELABORACION\PAPER_FanCatchments/Data/Spatial/Vector/gdf.shp', mode="w")